version: '3'
services:
  shogun-postgis:
    image: mdillon/postgis:10-alpine
    ports:
      - 5555:5432
    environment:
      POSTGRES_USER: gondolin
      POSTGRES_PASSWORD: gondolin
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data:Z
